baseURL = 'https://mahmoudmabrouk.com'
languageCode = 'en-us'
title = 'Mahmoud Mabrouk Personal Webpage'
Theme = 'hugo-theme-nix'
[params]
  Name = "Mahmoud Mabrouk"
  HeaderUsername = "mahmoud"
  HeaderHostname = "mabrouk"
  About = " Exploring how to bring LLMs, chatbots and agents to production | Prev: Founding ML Eng @ModelMe , PhD candidate RBOLab @TUBerlin "
  ProfilePicture = "portrait_real.jpeg"
  Email = "mahmoudmabrouk.mail[at]gmail.com"
  GithubID="mmabrouk"
  LinkedInID = "mmabrouk2"
  TwitterID = "mmabrouk_"
  TwitchID = "resiros"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"


  

